apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc:8200
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: external-secrets
            namespace: flux-system
