apiVersion: v1
kind: ServiceAccount
metadata:
  name: woodpecker-agent
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker-agent
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: woodpecker-agent
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker-agent
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - persistentvolumeclaims
      - services
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: woodpecker-agent
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker-agent
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: woodpecker-agent
subjects:
  - kind: ServiceAccount
    name: woodpecker-agent
    namespace: woodpecker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: woodpecker-agent
  namespace: woodpecker-pipelines
  labels:
    app.kubernetes.io/name: woodpecker-agent
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - persistentvolumeclaims
      - services
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: woodpecker-agent
  namespace: woodpecker-pipelines
  labels:
    app.kubernetes.io/name: woodpecker-agent
    app.kubernetes.io/part-of: kudofools
    app.kubernetes.io/managed-by: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: woodpecker-agent
subjects:
  - kind: ServiceAccount
    name: woodpecker-agent
    namespace: woodpecker
